pool:
  name: Azure Pipelines
  demands: npm
  vmImage: 'ubuntu-latest'

steps:
- powershell: |
    gci env:
    pwd
    gci . -recurse
  displayName: 'get env vars'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: ./extension
    verbose: false

- task: Bash@3
  displayName: Compile Javascript
  inputs:
    targetType: "inline"
    script: |
      cd extension
      tsc

- powershell: |
   & .\node_modules\.bin\tsc.cmd -p .\tsconfig.json

  workingDirectory: ./extension
  displayName: 'Compile code'
  enabled: false
  env:
    system.debug: true

- task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@3
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.7.x'
  enabled: false

- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: '.'
    outputPath: './MachineIdentityExtension.vsix'
    updateTasksVersion: false
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: MachineIdentityExtension'
  inputs:
    PathtoPublish: .
    ArtifactName: 'MachineIdentityExtension'
