pool:
  name: Azure Pipelines
  demands: npm
  vmImage: 'windows-latest'

steps:
- powershell: |
    gci env:
    pwd
    gci . -recurse
  displayName: 'get env vars'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: ./buildAndReleaseTask
    verbose: false

- powershell: |
   & .\node_modules\.bin\tsc.cmd -p .\tsconfig.json

  workingDirectory: ./buildAndReleaseTask
  displayName: 'Compile code'
  env:
    system.debug: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: VcertExtension'
  inputs:
    PathtoPublish: .
    ArtifactName: 'VcertExtension'

- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: '.'
    outputPath: './VcertExtension.vsix'
    updateTasksVersion: false